version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: orient base dir
          command: pwd
      - run:
          name: identify repo objects 
          command: ls
      - add_ssh_keys:
          fingerprints:
            - "8a:bf:e9:01:4c:05:f0:71:4c:d5:4e:5c:b1:91:aa:c3"
      - run: echo "deb  http://deb.debian.org/debian  stretch main" >> /etc/apt/sources.list
      - run: echo "deb-src  http://deb.debian.org/debian  stretch main" >> /etc/apt/sources.list
      - run: cat /etc/apt/sources.list
      - run: apt update
      - run:
          name: Install SCP 
          command: apt -y install openssh-client 
      - run:
          name: Execute SCP to EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -r /root/project/scptest.txt centos@52.91.123.248:/home/centos
            scp -r /root/project/scptest.txt centos@34.239.85.57:/home/centos
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Execute SCP to EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -r /root/project/scptest.txt centos@52.91.123.248:/home/centos
            scp -r /root/project/scptest.txt centos@34.239.85.57:/home/centos
      
